[devices.minithruster.vars]
#DepthFore = "motor_desires.fore_port"
#DepthAft = "motor_desires.aft_starboard"
#SwayPort = "motor_desires.sway_aft"
#SwayStarboard = "motor_desires.sway_fore"
#SurgePort = "motor_desires.port"
#SurgeStarboard = "motor_desires.starboard"

DepthFore = "motor_desires.sway_aft"
DepthAft = "motor_desires.port"
SwayPort = "motor_desires.fore_port"
SwayStarboard = "motor_desires.starboard"
SurgePort = "motor_desires.aft_starboard"
SurgeStarboard = "motor_desires.sway_fore"
